// <auto-generated />
namespace PrsWebAppProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tookoutcodeinpurchaserequestlineitemcs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tookoutcodeinpurchaserequestlineitemcs));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041857212_took out code in purchaserequestlineitem.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
